# Generated by Django 6.1 on 2026-09-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cardapi_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('cardapi_slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('network', models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover')], max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, choices=[('personal', 'Personal'), ('business', 'Business'), ('student', 'Student'), ('secured', 'Secured')], max_length=20, null=True)),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_fee_waived_first_year', models.BooleanField(blank=True, null=True)),
                ('foreign_transaction_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('credit_score_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reward_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('reward_currency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('application_rules', models.TextField(blank=True, null=True)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('curated_sources', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('incentive', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cardapi_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('curated_sources', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('perk', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CCIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='cardapi.creditcard')),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='cardapi.incentive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creditcard',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='cardapi.issuer'),
        ),
        migrations.CreateModel(
            name='CCPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='cardapi.creditcard')),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='cardapi.perk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CCRewardRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cardapi_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('rate_multiplier', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate_type', models.CharField(choices=[('multiplier', 'Multiplier'), ('percent_cashback', 'Percent cashback'), ('points_per_dollar', 'Points per dollar')], max_length=32)),
                ('cap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cap_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=32, null=True)),
                ('fallback_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_base_rate', models.BooleanField(default=False)),
                ('is_rotating', models.BooleanField(default=False)),
                ('rotating_quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rotating_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cardapi_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rates', to='cardapi.creditcard')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_rates', to='cardapi.rewardcategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('credit_card', 'source_key'), name='unique_card_reward_source_key')],
            },
        ),
        migrations.CreateModel(
            name='SignupBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('offer_text', models.TextField()),
                ('reported_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('minimum_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_spend_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(max_length=64)),
                ('source_type', models.CharField(choices=[('cardapi', 'CardAPI'), ('curated', 'Curated')], max_length=20)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_bonuses', to='cardapi.creditcard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('credit_card', 'source_type', 'source_key'), name='unique_card_signup_bonus_source')],
            },
        ),
    ]
