# Generated by Django 6.1 on 2026-09-02 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapi', '0008_remap_existing_reward_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('points', 'Points'), ('miles', 'Miles'), ('cash', 'Cash back')], max_length=20)),
                ('cash_value_cpp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('travel_portal_cpp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('transfer_value_cpp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_programs', to='cardapi.issuer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardRewardProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('can_cash_redeem', models.BooleanField(default=False)),
                ('can_use_travel_portal', models.BooleanField(default=False)),
                ('can_transfer_partners', models.BooleanField(default=False)),
                ('can_combine_rewards', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_program_memberships', to='cardapi.creditcard')),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_memberships', to='cardapi.rewardprogram')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('credit_card', 'reward_program'), name='unique_card_reward_program')],
            },
        ),
        migrations.CreateModel(
            name='RewardProgramUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('transfer_partners', 'Transfer partners'), ('travel_portal', 'Travel portal')], max_length=32)),
                ('conversion_ratio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('source_url', models.URLField()),
                ('verified_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('required_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_unlock_requirements', to='cardapi.creditcard')),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_rules', to='cardapi.rewardprogram')),
                ('source_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_unlock_sources', to='cardapi.creditcard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reward_program', 'source_card', 'required_card', 'capability'), name='unique_reward_program_unlock')],
            },
        ),
    ]
