# Generated by Django 6.1 on 2026-09-08 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapi', '0013_reward_transfer_route'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedCardCreditUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owned_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_uses', to='wallet.ownedcard')),
                ('statement_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cardapi.statementcredit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owned_card', 'statement_credit'), name='unique_credit_use_per_owned_card')],
            },
        ),
    ]
